# -*- coding: utf-8 -*-
"""array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdunxiLri9nDABZnmxHzOKnR5VE56yEc
"""

#Membuat array

import array as arr

a = arr.array('i', [1, 2, 3])
print("The new created array is : ", end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()

b = arr.array('d', [1.2, 3.4, 5.6])
print("\nThe New created array is : ", end=" ")
for i in range(0,3):
  print(b[i], end=" ")

#Menambahkan elemen array
from array import array

#insert
a = array("i", [1, 2, 3])
print("Array before insertion :", end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()

a.insert(1, 4)
print("array after insert :", end=" ")
for i in (a):
  print(i, end=" ")

print()
#append
b = array("d", [1.2, 2.3, 3.4])
print("Array before append :", end=" ")
for i in range(3):
  print(b[i], end=" ")
print()

b.append(4.5)
print("Array after append:", end=" ")
for i in (b):
  print(i, end=" ")
print()

#mengakses elemen array
from array import array

a = array('i', [1,2,3,4,5,6])
print("elemen a indeks ke 0: ", a[0])
print("elemen a indeks ke 2: ", a[2])

b = array("d", [1.2, 2.3, 3.4, 4.5, 5.6])
print("elemen b index ke 3: ", b[1])
print("elemen b index ke 5 ", b[4])

#menghapus elemen array
from array import array as arr

a = arr("i", [1,2,3,1,5])
print("Array saat ini adalah: ", end="")
for i in range(0,5):
  print(a[i], end=" ")

print('\r')
print('Elemen yang di pop: ', end="")
print(a.pop(2)) #by index
print('Array setelah di pop: ', end="")
for i in range(0,4):
  print(a[i], end=" ")

print('\r')
a.remove(1) #by element
print('Array setelah di remove adalah: ', end='')
for i in range(0,3):
  print(a[i], end=' ')

from array import array as arr
l = [1,2,3,4,5,6,7,8,9,10]

a = arr('i', l)
print("Array init: ")
for i in (a):
  print(i, end=' ')

sliced_arr = a[4:8]
print('\nSlicing element range 4-8: ')
print(sliced_arr)

sliced_arr = a[6:]
print('\nElement from 6th till the end: ')
print(sliced_arr)

sliced_arr = a[:]
print('\nPrint all element using slice operation: ')
print(sliced_arr)

#mengubah elemen array
from array import array as arr

a = arr('i', [1,2,3,1,2,5])
print("Array before updation: ", end="")
for i in range(0,6):
  print(a[i], end=" ")

print('\r')
a[2] = 6
print('Array after updation: ', end="")
for i in range(0,6):
  print(a[i], end=" ")
print()

a[4] = 8
print("Array after updation: ", end="")
for i in range(0,6):
  print(a[i], end=" ")

#operasi array
from array import array as arr
a = arr('i', [1,2,3,4,2,5,2])

#Menghitung elemen array
count = a.count(2)
print('Number of occurences of 2:',count)

#membalik elemen array
print('Original array:', *a)
a.reverse()
print('Reversed array:',*a)

#extend dalam array
from array import array as arr

#iinteger
a = arr('i', [1,2,3,4,5])
print('Array before extend: ', end=' ')
for i in range (0,5):
  print(a[i], end=' ')
print()

a.extend([6,7,8,9,10])
print('\nArray after extend: ', end=' ')
for i in range(0,10):
  print(a[i], end=' ')
print()

#double
b = arr('d', [1.2, 2.3, 3.4, 4.5, 5.6])
print('\nArray before extend: ', end=' ')
for i in (b):
  print(i, end=' ')
print()

b.extend([6.7, 7.8, 8.9, 9.10])
print('\nArray after extend: ', end=' ')
for i in (b):
  print(i, end=' ')
print()